namespace SourceGenerator;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator(LanguageNames.CSharp)]
public sealed class HelloIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MainMethodInfo> provider = context.SyntaxProvider
            .CreateSyntaxProvider(IsMainLikeInPartialClass, ExtractMainMethodInfo)
            .Where(static mainInfo => mainInfo is not null)
            .Select((symbol, _) => symbol!)
            .WithComparer(EqualityComparer<MainMethodInfo>.Default);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static bool IsMainLikeInPartialClass(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        return syntaxNode is MethodDeclarationSyntax candidate &&
               !candidate.Modifiers.Any(SyntaxKind.PartialKeyword) &&
               candidate.Modifiers.Any(SyntaxKind.StaticKeyword) &&
               candidate.Identifier.Text == "Main" &&
               candidate.Parent is ClassDeclarationSyntax parentClass &&
               parentClass.Modifiers.Any(SyntaxKind.PartialKeyword);
    }

    private static MainMethodInfo? ExtractMainMethodInfo(
        GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        Debug.Assert(context.Node is MethodDeclarationSyntax);
        var candidate = Unsafe.As<MethodDeclarationSyntax>(context.Node);

        IMethodSymbol? symbol = context.SemanticModel.GetDeclaredSymbol(candidate, cancellationToken);

        if (symbol is not null && symbol.Name == "Main")
        {
            return new MainMethodInfo(symbol.ContainingNamespace.ToDisplayString(), symbol.ContainingType.Name);
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, MainMethodInfo mainMethod)
    {
        // lang=C#
        string source = $$"""
            // <auto-generated/>

            namespace {{mainMethod.NamespaceName}};

            public static partial class {{mainMethod.ClassName}}
            {
                static void HelloFrom(string name) =>
                    global::System.Console.WriteLine($"Generator says: Hi from '{name}'");
            }
            """;

        string hintName = string.Join(
            ".",
            mainMethod.NamespaceName,
            mainMethod.ClassName,
            "g.cs");

        context.AddSource(hintName, source);
    }

    private record MainMethodInfo
    {
        public MainMethodInfo(string namespaceName, string className)
        {
            this.NamespaceName = namespaceName;
            this.ClassName = className;
        }

        public string NamespaceName { get; }
        public string ClassName { get; }
    }
}